IFACE_EXCLUDE="lo tun+ tap+ wg+ ppp+ ipsec+ ifb+ dummy+"
ISP_INTERFACE=""

NFQWS_BASE_ARGS="--lua-init=@$LUA_DIR/zapret-lib.lua
                 --lua-init=@$LUA_DIR/zapret-antidpi.lua
                 --lua-init=@$LUA_DIR/zapret-auto.lua
                 --blob=quic_google:@$BLOBS_DIR/quic_initial_www_google_com.bin
                 --blob=tls_max:@$BLOBS_DIR/tls_clienthello_max_ru.bin
                 --blob=discord_udp:@$BLOBS_DIR/ACTIVE_DISCORD_UDP.bin
                 --blob=game_udp:@$BLOBS_DIR/ACTIVE_GAME_UDP.bin"

NFQWS_ARGS="--filter-tcp=80,443 --filter-l7=http,tls
            --payload=tls_client_hello
            --lua-desync=fake:blob=fake_default_tls:tls_mod=rnd,dupsid,sni=ya.ru:tcp_ts=-600000:tcp_ts_up
            --lua-desync=hostfakesplit:host=ya.ru:tcp_ts=-600000:tcp_ts_up
            --payload=http_req
            --lua-desync=fake:blob=tls_max:tcp_ts=-600000:tcp_ts_up
            --lua-desync=hostfakesplit:host=ya.ru:tcp_ts=-600000:tcp_ts_up"

NFQWS_ARGS_QUIC="--filter-udp=443 --filter-l7=quic
                 --payload=quic_initial
                 --lua-desync=fake:blob=quic_google:repeats=6"

NFQWS_ARGS_UDP="--filter-udp=19294-19344,50000-50100 --filter-l7=discord,stun
                --payload=discord_ip_discovery,stun
                --lua-desync=fake:blob=discord_udp:repeats=6"

MODE_LIST="--hostlist=$LISTS_DIR/user.list"
MODE_ALL="--hostlist-exclude=$LISTS_DIR/exclude.list"
MODE_AUTO="$MODE_LIST --hostlist-auto=$LISTS_DIR/auto.list --hostlist-auto-debug=$LOG_DIR/auto.log $MODE_ALL"
NFQWS_EXTRA_ARGS="$MODE_AUTO"
NFQWS_ARGS_IPSET="--ipset=$LISTS_DIR/ipset.list --ipset-exclude=$LISTS_DIR/ipset_exclude.list"

NFQWS_ARGS_CUSTOM="--filter-tcp=2053,2083,2087,2096,8443 --filter-l7=tls --hostlist-domains=discord.media
                   --payload=tls_client_hello
                   --lua-desync=fake:blob=fake_default_tls:tls_mod=rnd,dupsid,sni=www.google.com:tcp_ts=-600000:tcp_ts_up
                   --lua-desync=hostfakesplit:host=www.google.com:tcp_ts=-600000:tcp_ts_up
                   --new
                   --filter-tcp=443 --filter-l7=tls --hostlist=$LISTS_DIR/google.list
                   --payload=tls_client_hello 
                   --lua-desync=fake:blob=fake_default_tls:tls_mod=rnd,dupsid,sni=www.google.com:ip_id=zero:tcp_ts=-600000:tcp_ts_up
                   --lua-desync=hostfakesplit:host=www.google.com:ip_id=zero:tcp_ts=-600000:tcp_ts_up"

IPV6_ENABLED=1
TCP_PORTS=80,443,1984,2053,2083,2087,2096,5222,8443
UDP_PORTS=443,590:600,1400,3478:3481,5349,19294:19344,49152:65535
NFQUEUE_NUM=300

PKT_LIMIT_OUT=15
PKT_LIMIT_IN=15

BLOCK_QUIC=0
NAT_FIX=1
APP_MODE=off
AUTOSTART=1
WATCHDOG=1
SAFE_START=1

NFQWS_USER=root
LOG_LEVEL=0
LOG_MAX_KB=512
CONFIG_VERSION=2