NAME=GeoHide DNS
DESC=eu.geohide.ru: DoH, DoT и обычный DNS
ENABLED=0
SERVER=https://eu.geohide.ru/dns-query
SERVER=tls://eu.geohide.ru
SERVER=5.175.161.3
SERVER=5.175.161.40
SERVER=45.13.237.213
SERVER=31.25.239.132
SERVER=143.20.64.192
