NAME=Instagram и Facebook
DESC=Сервисы Meta через DoH opennameserver.org
ENABLED=0
SERVER=https://ns2.opennameserver.org/dns-query
DOMAIN=instagram.com
DOMAIN=cdninstagram.com
DOMAIN=ig.me
DOMAIN=facebook.com
DOMAIN=fb.com
DOMAIN=facebook.net
DOMAIN=fbcdn.net
DOMAIN=fbsbx.com
DOMAIN=threads.net
DOMAIN=threads.com
